import type { Blueprint, Dependency, Modifier } from '@satellite-games/orbit';
import type { CharacterSkill, PrimaryAttribute, SecondaryAttribute } from '@/main';
import type { CharacterAbility } from './ability.go';

export const characterAbilities: Array<
  Blueprint<CharacterAbility, 'needsDetails' | 'details' | 'castTime' | 'resourceUse'> & {
    needsDetails?: boolean;
    castTime?: number;
    resourceUse?: number;
  }
> = [
  {
    name: 'character.ability.armor-habituation-1',
    category: 'character.ability-category.general',
    usageType: 'character.ability-usage-type.passive',
    cost: 100,
    dependencies: [
      {
        name: 'character.primary-attribute.constitution',
        key: 'current',
        value: 12,
      } as Dependency<PrimaryAttribute>,
    ],
  },
  {
    name: 'character.ability.armor-habituation-2',
    category: 'character.ability-category.general',
    usageType: 'character.ability-usage-type.passive',
    cost: 200,
    dependencies: [
      {
        name: 'character.primary-attribute.constitution',
        key: 'current',
        value: 14,
      } as Dependency<PrimaryAttribute>,
      {
        name: 'character.primary-attribute.strength',
        key: 'current',
        value: 12,
      } as Dependency<PrimaryAttribute>,
      {
        name: 'character.ability.armor-habituation-1',
      } as Dependency<CharacterAbility>,
    ],
  },
  {
    name: 'character.ability.armor-habituation-3',
    category: 'character.ability-category.general',
    usageType: 'character.ability-usage-type.passive',
    cost: 300,
    dependencies: [
      {
        name: 'character.primary-attribute.constitution',
        key: 'current',
        value: 15,
      } as Dependency<PrimaryAttribute>,
      {
        name: 'character.primary-attribute.strength',
        key: 'current',
        value: 14,
      } as Dependency<PrimaryAttribute>,
      {
        name: 'character.ability.armor-habituation-2',
      } as Dependency<CharacterAbility>,
    ],
  },
  {
    name: 'character.ability.combat-experience',
    category: 'character.ability-category.general',
    usageType: 'character.ability-usage-type.passive',
    cost: 400,
    dependencies: [
      {
        name: 'character.primary-attribute.dexterity',
        key: 'current',
        value: 8,
      } as Dependency<PrimaryAttribute>,
    ],
  },
  {
    name: 'character.ability.implant-habituation-1',
    category: 'character.ability-category.general',
    usageType: 'character.ability-usage-type.passive',
    cost: 100,
    dependencies: [
      {
        name: 'character.primary-attribute.constitution',
        key: 'current',
        value: 12,
      } as Dependency<PrimaryAttribute>,
    ],
  },
  {
    name: 'character.ability.implant-habituation-2',
    category: 'character.ability-category.general',
    usageType: 'character.ability-usage-type.passive',
    cost: 200,
    dependencies: [
      {
        name: 'character.primary-attribute.intuition',
        key: 'current',
        value: 12,
      } as Dependency<PrimaryAttribute>,
      {
        name: 'character.primary-attribute.constitution',
        key: 'current',
        value: 14,
      } as Dependency<PrimaryAttribute>,
      {
        name: 'character.ability.implant-habituation-1',
      } as Dependency<CharacterAbility>,
    ],
  },
  {
    name: 'character.ability.language',
    category: 'character.ability-category.general',
    usageType: 'character.ability-usage-type.passive',
    needsDetails: true,
    cost: 100,
  },
  {
    name: 'character.ability.local-knowledge',
    category: 'character.ability-category.general',
    usageType: 'character.ability-usage-type.passive',
    needsDetails: true,
    cost: 100,
  },
  {
    name: 'character.ability.master-of-improvisation',
    category: 'character.ability-category.general',
    usageType: 'character.ability-usage-type.passive',
    cost: 200,
    dependencies: [
      {
        name: 'character.primary-attribute.intuition',
        key: 'current',
        value: 12,
      } as Dependency<PrimaryAttribute>,
      {
        name: 'character.primary-attribute.dexterity',
        key: 'current',
        value: 12,
      } as Dependency<PrimaryAttribute>,
    ],
  },
  {
    name: 'character.ability.mid-hacking',
    category: 'character.ability-category.general',
    usageType: 'character.ability-usage-type.passive',
    cost: 300,
    dependencies: [
      {
        name: 'skill/knowledge/information-technology',
        key: 'current',
        value: 7,
      } as Dependency<CharacterSkill>,
      {
        name: 'skill/crafting/programming',
        key: 'current',
        value: 3,
      } as Dependency<CharacterSkill>,
    ],
  },
  {
    name: 'character.ability.quick-drawing',
    category: 'character.ability-category.general',
    usageType: 'character.ability-usage-type.passive',
    cost: 200,
    dependencies: [
      {
        name: 'character.primary-attribute.agility',
        key: 'current',
        value: 12,
      } as Dependency<PrimaryAttribute>,
      {
        name: 'character.primary-attribute.dexterity',
        key: 'current',
        value: 10,
      } as Dependency<PrimaryAttribute>,
    ],
  },
  {
    name: 'character.ability.reflexes-1',
    category: 'character.ability-category.general',
    usageType: 'character.ability-usage-type.passive',
    cost: 300,
    dependencies: [
      {
        name: 'character.primary-attribute.intuition',
        key: 'current',
        value: 12,
      } as Dependency<PrimaryAttribute>,
      {
        name: 'character.secondary-attribute.reaction',
        key: 'total',
        value: 10,
      } as Dependency<SecondaryAttribute>,
    ],
    modifiers: [
      {
        targetName: 'character.secondary-attribute.reaction',
        keys: 'total',
        amount: 4,
      } as Modifier<SecondaryAttribute>,
    ],
  },
  {
    name: 'character.ability.reflexes-2',
    category: 'character.ability-category.general',
    usageType: 'character.ability-usage-type.passive',
    cost: 200,
    dependencies: [
      {
        name: 'character.primary-attribute.intuition',
        key: 'current',
        value: 15,
      } as Dependency<PrimaryAttribute>,
      {
        name: 'skill/knowledge/tactics-and-strategy',
        key: 'current',
        value: 3,
      } as Dependency<CharacterSkill>,
      {
        name: 'character.ability.reflexes-1',
      } as Dependency<CharacterAbility>,
    ],
    modifiers: [
      {
        targetName: 'character.secondary-attribute.reaction',
        keys: ['total'],
        amount: 2,
      } as Modifier<SecondaryAttribute>,
    ],
  },
  {
    name: 'character.ability.steady',
    category: 'character.ability-category.general',
    usageType: 'character.ability-usage-type.passive',
    cost: 100,
    dependencies: [
      {
        name: 'character.primary-attribute.agility',
        key: 'current',
        value: 12,
      } as Dependency<PrimaryAttribute>,
    ],
  },
  {
    name: 'character.ability.strong-nerves',
    category: 'character.ability-category.general',
    usageType: 'character.ability-usage-type.passive',
    cost: 200,
    dependencies: [
      {
        name: 'character.primary-attribute.courage',
        key: 'current',
        value: 12,
      } as Dependency<PrimaryAttribute>,
    ],
  },
  {
    name: 'character.ability.vti-commanding',
    category: 'character.ability-category.general',
    usageType: 'character.ability-usage-type.passive',
    cost: 300,
    dependencies: [
      {
        name: 'skill/knowledge/tactics-and-strategy',
        key: 'current',
        value: 7,
      } as Dependency<CharacterSkill>,
    ],
  },
  {
    name: 'character.ability.wealth-of-knowledge',
    category: 'character.ability-category.general',
    usageType: 'character.ability-usage-type.passive',
    cost: 200,
    dependencies: [
      {
        name: 'character.primary-attribute.cleverness',
        key: 'current',
        value: 12,
      } as Dependency<PrimaryAttribute>,
      {
        name: 'character.primary-attribute.intuition',
        key: 'current',
        value: 12,
      } as Dependency<PrimaryAttribute>,
    ],
  },
  {
    name: 'character.ability.aimed-strike',
    category: 'character.ability-category.melee-combat-combat',
    usageType: 'character.ability-usage-type.uses-stamina',
    castTime: 1,
    resourceUse: 1,
    cost: 100,
    dependencies: [
      {
        name: 'character.primary-attribute.agility',
        key: 'current',
        value: 13,
      } as Dependency<PrimaryAttribute>,
    ],
  },
  {
    name: 'character.ability.breakaway',
    category: 'character.ability-category.melee-combat',
    usageType: 'character.ability-usage-type.uses-stamina',
    castTime: 1,
    resourceUse: 3,
    cost: 100,
    dependencies: [
      {
        name: 'character.primary-attribute.courage',
        key: 'current',
        value: 12,
      } as Dependency<PrimaryAttribute>,
      {
        name: 'character.primary-attribute.strength',
        key: 'current',
        value: 15,
      } as Dependency<PrimaryAttribute>,
      {
        name: 'character.ability.power-attack',
      } as Dependency<CharacterAbility>,
    ],
  },
  {
    name: 'character.ability.disarming',
    category: 'character.ability-category.melee-combat',
    dependencies: [
      {
        name: 'character.primary-attribute.strength',
        type: '',
        input: '',
        level: 13,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.ability.ImprovedParrying',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 1,
    staminaUse: 2,
    usesPower: false,
    cost: 200,
  },
  {
    name: 'character.ability.evasion-1',
    category: 'character.ability-category.melee-combat',
    dependencies: [
      {
        name: 'character.primary-attribute.agility',
        type: '',
        input: '',
        level: 10,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 300,
  },
  {
    name: 'character.ability.evasion-2',
    category: 'character.ability-category.melee-combat',
    dependencies: [
      {
        name: 'character.primary-attribute.agility',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.ability.evasion-1',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 200,
  },
  {
    name: 'character.ability.evasion-3',
    category: 'character.ability-category.melee-combat',
    dependencies: [
      {
        name: 'character.primary-attribute.agility',
        type: '',
        input: '',
        level: 15,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.ability.evasion-2',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 200,
  },
  {
    name: 'character.ability.feint',
    category: 'character.ability-category.melee-combat',
    dependencies: [
      {
        name: 'character.ability.aimed-strike',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 1,
    staminaUse: 1,
    usesPower: false,
    cost: 200,
  },
  {
    name: 'character.ability.full-attack',
    category: 'character.ability-category.melee-combat',
    dependencies: [
      {
        name: 'character.primary-attribute.constitution',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.ability.power-attack',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 2,
    staminaUse: 4,
    usesPower: false,
    cost: 200,
  },
  {
    name: 'character.ability.ImprovedParrying',
    category: 'character.ability-category.melee-combat',
    dependencies: [
      {
        name: 'character.primary-attribute.strength',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.primary-attribute.dexterity',
        type: '',
        input: '',
        level: 8,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 1,
    staminaUse: 2,
    usesPower: false,
    cost: 100,
  },
  {
    name: 'character.ability.KnockingDown',
    category: 'character.ability-category.melee-combat',
    dependencies: [
      {
        name: 'character.primary-attribute.strength',
        type: '',
        input: '',
        level: 14,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.ability.power-attack',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 1,
    staminaUse: 2,
    usesPower: false,
    cost: 100,
  },
  {
    name: 'character.ability.power-attack',
    category: 'character.ability-category.melee-combat',
    dependencies: [
      {
        name: 'character.primary-attribute.strength',
        type: '',
        input: '',
        level: 13,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 1,
    staminaUse: 2,
    usesPower: false,
    cost: 100,
  },
  {
    name: 'character.ability.Resisting',
    category: 'character.ability-category.melee-combat',
    dependencies: [
      {
        name: 'character.primary-attribute.courage',
        type: '',
        input: '',
        level: 15,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.primary-attribute.agility',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.ability.ImprovedParrying',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 1,
    staminaUse: 2,
    usesPower: false,
    cost: 200,
  },
  {
    name: 'character.ability.StunningStrike',
    category: 'character.ability-category.melee-combat',
    dependencies: [
      {
        name: 'character.primary-attribute.agility',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.ability.power-attack',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 1,
    staminaUse: 2,
    usesPower: false,
    cost: 100,
  },
  {
    name: 'character.ability.TwohandedMelee',
    category: 'character.ability-category.melee-combat',
    dependencies: [
      {
        name: 'character.primary-attribute.agility',
        type: '',
        input: '',
        level: 15,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.primary-attribute.strength',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.ability.aimed-strike',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 400,
  },
  {
    name: 'ability/ranged/accurate',
    category: 'character.ability-category.ranged',
    dependencies: [
      {
        name: 'ability/ranged/precision-shot-1',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 200,
  },
  {
    name: 'ability/ranged/barrage-fire',
    category: 'character.ability-category.ranged',
    dependencies: [
      {
        name: 'character.primary-attribute.constitution',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.primary-attribute.strength',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/ranged/precision-shot-1',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 2,
    staminaUse: 4,
    usesPower: false,
    cost: 200,
  },
  {
    name: 'ability/ranged/experienced-heavy-weapons-user',
    category: 'character.ability-category.ranged',
    dependencies: [
      {
        name: 'character.primary-attribute.constitution',
        type: '',
        input: '',
        level: 13,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.primary-attribute.strength',
        type: '',
        input: '',
        level: 13,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 100,
  },
  {
    name: 'ability/ranged/focus',
    category: 'character.ability-category.ranged',
    dependencies: [
      {
        name: 'character.primary-attribute.intuition',
        type: '',
        input: '',
        level: 13,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.primary-attribute.agility',
        type: '',
        input: '',
        level: 13,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/ranged/precision-shot-1',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 300,
  },
  {
    name: 'ability/ranged/precision-shot-1',
    category: 'character.ability-category.ranged',
    dependencies: [
      {
        name: 'character.primary-attribute.dexterity',
        type: '',
        input: '',
        level: 13,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 1,
    staminaUse: 1,
    usesPower: false,
    cost: 100,
  },
  {
    name: 'ability/ranged/precision-shot-2',
    category: 'character.ability-category.ranged',
    dependencies: [
      {
        name: 'character.primary-attribute.dexterity',
        type: '',
        input: '',
        level: 14,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/ranged/precision-shot-1',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 2,
    staminaUse: 2,
    usesPower: false,
    cost: 200,
  },
  {
    name: 'ability/ranged/precision-shot-3',
    category: 'character.ability-category.ranged',
    dependencies: [
      {
        name: 'character.primary-attribute.dexterity',
        type: '',
        input: '',
        level: 15,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/ranged/precision-shot-2',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 3,
    staminaUse: 3,
    usesPower: false,
    cost: 400,
  },
  {
    name: 'ability/ranged/prepare-attack',
    category: 'character.ability-category.ranged',
    dependencies: [
      {
        name: 'character.primary-attribute.courage',
        type: '',
        input: '',
        level: 13,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.primary-attribute.agility',
        type: '',
        input: '',
        level: 13,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.ability.reflexes-1',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    staminaUse: 1,
    usesPower: false,
    cost: 200,
  },
  {
    name: 'ability/ranged/twohanded-ranged',
    category: 'character.ability-category.ranged',
    dependencies: [
      {
        name: 'character.primary-attribute.agility',
        type: '',
        input: '',
        level: 15,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.primary-attribute.dexterity',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.ability.reflexes-1',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 500,
  },
  {
    name: 'ability/vehicles/barrel-roll',
    category: 'character.ability-category.vehicles',
    dependencies: [
      {
        name: 'character.primary-attribute.courage',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.primary-attribute.constitution',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'skill/vehicles/extraplanetary-flying',
        type: '',
        input: '',
        level: 5,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'skill/vehicles/intraplanetary-flying',
        type: '',
        input: '',
        level: 3,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    usesPower: true,
    powerUse: 1,
    cost: 200,
  },
  {
    name: 'ability/vehicles/broadside',
    category: 'character.ability-category.vehicles',
    dependencies: [
      {
        name: 'character.primary-attribute.intuition',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'skill/vehicles/extraplanetary-flying',
        type: '',
        input: '',
        level: 5,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'skill/vehicles/intraplanetary-flying',
        type: '',
        input: '',
        level: 3,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    usesPower: true,
    powerUse: 1,
    cost: 200,
  },
  {
    name: 'ability/vehicles/dive-attack',
    category: 'character.ability-category.vehicles',
    dependencies: [
      {
        name: 'character.primary-attribute.courage',
        type: '',
        input: '',
        level: 13,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.primary-attribute.intuition',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'skill/vehicles/extraplanetary-flying',
        type: '',
        input: '',
        level: 5,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'skill/vehicles/intraplanetary-flying',
        type: '',
        input: '',
        level: 3,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    usesPower: true,
    powerUse: 2,
    cost: 200,
  },
  {
    name: 'ability/vehicles/flying-ace',
    category: 'character.ability-category.vehicles',
    dependencies: [
      {
        name: 'character.primary-attribute.intuition',
        type: '',
        input: '',
        level: 13,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.primary-attribute.constitution',
        type: '',
        input: '',
        level: 15,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'skill/vehicles/extraplanetary-flying',
        type: '',
        input: '',
        level: 10,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'skill/vehicles/intraplanetary-flying',
        type: '',
        input: '',
        level: 5,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 500,
  },
  {
    name: 'ability/vehicles/low-level-flight',
    category: 'character.ability-category.vehicles',
    dependencies: [
      {
        name: 'character.primary-attribute.courage',
        type: '',
        input: '',
        level: 14,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/vehicles/outmaneuvering-1',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    usesPower: true,
    powerUse: 2,
    cost: 300,
  },
  {
    name: 'ability/vehicles/luring-flight',
    category: 'character.ability-category.vehicles',
    dependencies: [
      {
        name: 'character.primary-attribute.courage',
        type: '',
        input: '',
        level: 14,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/vehicles/barrel-roll',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 1,
    usesPower: true,
    powerUse: 2,
    cost: 200,
  },
  {
    name: 'ability/vehicles/onboard-marksman-1',
    category: 'character.ability-category.ranged',
    dependencies: [
      {
        name: 'skill/combat/onboard-weapons',
        type: '',
        input: '',
        level: 5,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 1,
    usesPower: true,
    powerUse: 1,
    cost: 100,
  },
  {
    name: 'ability/vehicles/onboard-marksman-2',
    category: 'character.ability-category.ranged',
    dependencies: [
      {
        name: 'skill/combat/onboard-weapons',
        type: '',
        input: '',
        level: 7,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/vehicles/onboard-marksman-1',
        type: '',
        input: '',
        level: 7,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 2,
    usesPower: true,
    powerUse: 2,
    cost: 200,
  },
  {
    name: 'ability/vehicles/onboard-marksman-3',
    category: 'character.ability-category.ranged',
    dependencies: [
      {
        name: 'skill/combat/onboard-weapons',
        type: '',
        input: '',
        level: 10,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/vehicles/onboard-marksman-2',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 3,
    usesPower: true,
    powerUse: 3,
    cost: 400,
  },
  {
    name: 'ability/vehicles/outmaneuvering-1',
    category: 'character.ability-category.vehicles',
    dependencies: [
      {
        name: 'character.primary-attribute.courage',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.primary-attribute.intuition',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'skill/vehicles/extraplanetary-flying',
        type: '',
        input: '',
        level: 7,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'skill/vehicles/intraplanetary-flying',
        type: '',
        input: '',
        level: 5,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    usesPower: true,
    powerUse: 2,
    cost: 200,
  },
  {
    name: 'ability/vehicles/outmaneuvering-2',
    category: 'character.ability-category.vehicles',
    dependencies: [
      {
        name: 'character.primary-attribute.intuition',
        type: '',
        input: '',
        level: 15,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.primary-attribute.constitution',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/vehicles/outmaneuvering-1',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    usesPower: true,
    powerUse: 3,
    cost: 200,
  },
  {
    name: 'ability/vehicles/rapid-turnaround',
    category: 'character.ability-category.vehicles',
    dependencies: [
      {
        name: 'character.primary-attribute.courage',
        type: '',
        input: '',
        level: 15,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/vehicles/barrel-roll',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 2,
    usesPower: true,
    powerUse: 3,
    cost: 300,
  },
  {
    name: 'ability/vehicles/save-driving-land-vehicles',
    category: 'character.ability-category.vehicles',
    dependencies: [
      {
        name: 'character.primary-attribute.courage',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.primary-attribute.intuition',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'skill/vehicles/land-vehicles',
        type: '',
        input: '',
        level: 7,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 100,
  },
  {
    name: 'ability/vehicles/save-driving-water-vehicles',
    category: 'character.ability-category.vehicles',
    dependencies: [
      {
        name: 'character.primary-attribute.courage',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.primary-attribute.intuition',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'skill/vehicles/water-vehicles',
        type: '',
        input: '',
        level: 7,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 100,
  },
];
