import type { Blueprint, Dependency, GameObjectName } from '@satellite-games/orbit';
import type { PrimaryAttribute } from '@/main';
import type { CharacterAbility } from './ability.go';

export const characterAbilities: Array<
  Blueprint<CharacterAbility, 'needsDetails' | 'details' | 'castTime' | 'resourceUse'> & {
    needsDetails?: boolean;
    castTime?: number;
    staminaUse?: number;
    powerUse?: number;
  }
> = [
  {
    name: 'character.ability.armor-habituation-1',
    category: 'character.ability-category.general',
    usageType: 'character.ability-usage-type.passive',
    cost: 100,
    dependencies: [
      {
        name: 'character.primary-attribute.constitution',
        key: 'current',
        value: 12,
      } as Dependency<PrimaryAttribute>,
    ],
  },
  {
    name: 'character.ability.armor-habituation-2',
    category: 'character.ability-category.general',
    usageType: 'character.ability-usage-type.passive',
    dependencies: [
      {
        name: 'character.primary-attribute.constitution',
        key: 'current',
        value: 14,
      } as Dependency<PrimaryAttribute>,
      {
        name: 'character.primary-attribute.strength',
        key: 'current',
        value: 12,
      } as Dependency<PrimaryAttribute>,
      {
        name: 'character.ability.armor-habituation-1',
      } as Dependency<CharacterAbility>,
    ],
    cost: 200,
  },
  {
    name: 'character.ability.armor-habituation-3',
    category: 'character.ability-category.general',
    dependencies: [
      {
        name: 'character.primary-attribute.constitution',
        type: '',
        input: '',
        level: 15,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.primary-attribute.strength',
        type: '',
        input: '',
        level: 14,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.ability.ArmorHabituation2',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 300,
  },
  {
    name: 'character.ability.combat-experience',
    category: 'character.ability-category.general',
    dependencies: [
      {
        name: 'character.primary-attribute.dexterity',
        type: '',
        input: '',
        level: 8,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 400,
  },
  {
    name: 'character.ability.implant-habituation-1',
    category: 'character.ability-category.general',
    dependencies: [
      {
        name: 'character.primary-attribute.constitution',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 100,
  },
  {
    name: 'character.ability.implant-habituation-2',
    category: 'character.ability-category.general',
    dependencies: [
      {
        name: 'pri-a/in',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.primary-attribute.constitution',
        type: '',
        input: '',
        level: 14,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.ability.ImplantHabituation1',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 200,
  },
  {
    name: 'character.ability.language',
    category: 'character.ability-category.general',
    dependencies: [],
    needsDetails: true,
    isActive: false,
    usesPower: false,
    cost: 100,
  },
  {
    name: 'character.ability.local-knowledge',
    category: 'character.ability-category.general',
    dependencies: [],
    needsDetails: true,
    isActive: false,
    usesPower: false,
    cost: 100,
  },
  {
    name: 'character.ability.master-of-improvisation',
    category: 'character.ability-category.general',
    dependencies: [
      {
        name: 'pri-a/in',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'pri-a/dx',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 200,
  },
  {
    name: 'character.ability.mid-hacking',
    category: 'character.ability-category.general',
    dependencies: [
      {
        name: 'skill/knowledge/information-technology',
        type: '',
        input: '',
        level: 7,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'skill/crafting/programming',
        type: '',
        input: '',
        level: 3,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 300,
  },
  {
    name: 'character.ability.quick-drawing',
    category: 'character.ability-category.general',
    dependencies: [
      {
        name: 'pri-a/ag',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'pri-a/dx',
        type: '',
        input: '',
        level: 10,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 200,
  },
  {
    name: 'character.ability.reflexes-1',
    category: 'character.ability-category.general',
    dependencies: [
      {
        name: 'pri-a/in',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'sec-a/re',
        type: '',
        input: '',
        level: 10,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 300,
    targets: [
      {
        name: 'sec-a/re',
        type: 'bonus',
        level: 4,
      },
    ],
  },
  {
    name: 'character.ability.reflexes-2',
    category: 'character.ability-category.general',
    dependencies: [
      {
        name: 'pri-a/in',
        type: '',
        input: '',
        level: 15,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'skill/knowledge/tactics-and-strategy',
        type: '',
        input: '',
        level: 3,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.ability.reflexes-1',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 200,
    targets: [
      {
        name: 'sec-a/re',
        type: 'bonus',
        level: 2,
      },
    ],
  },
  {
    name: 'character.ability.steady',
    category: 'character.ability-category.general',
    dependencies: [
      {
        name: 'pri-a/ag',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 100,
  },
  {
    name: 'character.ability.strong-nerves',
    category: 'character.ability-category.general',
    dependencies: [
      {
        name: 'pri-a/cr',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 200,
  },
  {
    name: 'character.ability.vti-commanding',
    category: 'character.ability-category.general',
    dependencies: [
      {
        name: 'skill/knowledge/tactics-and-strategy',
        type: '',
        input: '',
        level: 7,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 300,
  },
  {
    name: 'character.ability.wealth-of-knowledge',
    category: 'character.ability-category.general',
    dependencies: [
      {
        name: 'pri-a/cl',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'pri-a/in',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 200,
  },
  {
    name: 'ability/melee/aimed-strike',
    category: 'character.ability-category.melee',
    dependencies: [
      {
        name: 'pri-a/ag',
        type: '',
        input: '',
        level: 13,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 1,
    staminaUse: 1,
    usesPower: false,
    cost: 100,
  },
  {
    name: 'ability/melee/breakaway',
    category: 'character.ability-category.melee',
    dependencies: [
      {
        name: 'pri-a/cr',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.primary-attribute.strength',
        type: '',
        input: '',
        level: 15,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/melee/PowerAttack',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 1,
    staminaUse: 3,
    usesPower: false,
    cost: 100,
  },
  {
    name: 'ability/melee/disarming',
    category: 'character.ability-category.melee',
    dependencies: [
      {
        name: 'character.primary-attribute.strength',
        type: '',
        input: '',
        level: 13,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/melee/ImprovedParrying',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 1,
    staminaUse: 2,
    usesPower: false,
    cost: 200,
  },
  {
    name: 'ability/melee/evasion-1',
    category: 'character.ability-category.melee',
    dependencies: [
      {
        name: 'pri-a/ag',
        type: '',
        input: '',
        level: 10,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 300,
  },
  {
    name: 'ability/melee/evasion-2',
    category: 'character.ability-category.melee',
    dependencies: [
      {
        name: 'pri-a/ag',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/melee/evasion-1',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 200,
  },
  {
    name: 'ability/melee/evasion-3',
    category: 'character.ability-category.melee',
    dependencies: [
      {
        name: 'pri-a/ag',
        type: '',
        input: '',
        level: 15,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/melee/evasion-2',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 200,
  },
  {
    name: 'ability/melee/feint',
    category: 'character.ability-category.melee',
    dependencies: [
      {
        name: 'ability/melee/aimed-strike',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 1,
    staminaUse: 1,
    usesPower: false,
    cost: 200,
  },
  {
    name: 'ability/melee/full-attack',
    category: 'character.ability-category.melee',
    dependencies: [
      {
        name: 'character.primary-attribute.constitution',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/melee/PowerAttack',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 2,
    staminaUse: 4,
    usesPower: false,
    cost: 200,
  },
  {
    name: 'ability/melee/ImprovedParrying',
    category: 'character.ability-category.melee',
    dependencies: [
      {
        name: 'character.primary-attribute.strength',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.primary-attribute.dexterity',
        type: '',
        input: '',
        level: 8,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 1,
    staminaUse: 2,
    usesPower: false,
    cost: 100,
  },
  {
    name: 'ability/melee/KnockingDown',
    category: 'character.ability-category.melee',
    dependencies: [
      {
        name: 'character.primary-attribute.strength',
        type: '',
        input: '',
        level: 14,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/melee/PowerAttack',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 1,
    staminaUse: 2,
    usesPower: false,
    cost: 100,
  },
  {
    name: 'ability/melee/PowerAttack',
    category: 'character.ability-category.melee',
    dependencies: [
      {
        name: 'character.primary-attribute.strength',
        type: '',
        input: '',
        level: 13,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 1,
    staminaUse: 2,
    usesPower: false,
    cost: 100,
  },
  {
    name: 'ability/melee/Resisting',
    category: 'character.ability-category.melee',
    dependencies: [
      {
        name: 'pri-a/cr',
        type: '',
        input: '',
        level: 15,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'pri-a/ag',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/melee/ImprovedParrying',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 1,
    staminaUse: 2,
    usesPower: false,
    cost: 200,
  },
  {
    name: 'ability/melee/StunningStrike',
    category: 'character.ability-category.melee',
    dependencies: [
      {
        name: 'pri-a/ag',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/melee/PowerAttack',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 1,
    staminaUse: 2,
    usesPower: false,
    cost: 100,
  },
  {
    name: 'ability/melee/TwohandedMelee',
    category: 'character.ability-category.melee',
    dependencies: [
      {
        name: 'pri-a/ag',
        type: '',
        input: '',
        level: 15,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.primary-attribute.strength',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/melee/aimed-strike',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 400,
  },
  {
    name: 'ability/ranged/accurate',
    category: 'character.ability-category.ranged',
    dependencies: [
      {
        name: 'ability/ranged/precision-shot-1',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 200,
  },
  {
    name: 'ability/ranged/barrage-fire',
    category: 'character.ability-category.ranged',
    dependencies: [
      {
        name: 'character.primary-attribute.constitution',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.primary-attribute.strength',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/ranged/precision-shot-1',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 2,
    staminaUse: 4,
    usesPower: false,
    cost: 200,
  },
  {
    name: 'ability/ranged/experienced-heavy-weapons-user',
    category: 'character.ability-category.ranged',
    dependencies: [
      {
        name: 'character.primary-attribute.constitution',
        type: '',
        input: '',
        level: 13,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.primary-attribute.strength',
        type: '',
        input: '',
        level: 13,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 100,
  },
  {
    name: 'ability/ranged/focus',
    category: 'character.ability-category.ranged',
    dependencies: [
      {
        name: 'pri-a/in',
        type: '',
        input: '',
        level: 13,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'pri-a/ag',
        type: '',
        input: '',
        level: 13,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/ranged/precision-shot-1',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 300,
  },
  {
    name: 'ability/ranged/precision-shot-1',
    category: 'character.ability-category.ranged',
    dependencies: [
      {
        name: 'pri-a/dx',
        type: '',
        input: '',
        level: 13,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 1,
    staminaUse: 1,
    usesPower: false,
    cost: 100,
  },
  {
    name: 'ability/ranged/precision-shot-2',
    category: 'character.ability-category.ranged',
    dependencies: [
      {
        name: 'pri-a/dx',
        type: '',
        input: '',
        level: 14,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/ranged/precision-shot-1',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 2,
    staminaUse: 2,
    usesPower: false,
    cost: 200,
  },
  {
    name: 'ability/ranged/precision-shot-3',
    category: 'character.ability-category.ranged',
    dependencies: [
      {
        name: 'pri-a/dx',
        type: '',
        input: '',
        level: 15,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/ranged/precision-shot-2',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 3,
    staminaUse: 3,
    usesPower: false,
    cost: 400,
  },
  {
    name: 'ability/ranged/prepare-attack',
    category: 'character.ability-category.ranged',
    dependencies: [
      {
        name: 'pri-a/cr',
        type: '',
        input: '',
        level: 13,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'pri-a/ag',
        type: '',
        input: '',
        level: 13,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.ability.reflexes-1',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    staminaUse: 1,
    usesPower: false,
    cost: 200,
  },
  {
    name: 'ability/ranged/twohanded-ranged',
    category: 'character.ability-category.ranged',
    dependencies: [
      {
        name: 'pri-a/ag',
        type: '',
        input: '',
        level: 15,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'pri-a/dx',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.ability.reflexes-1',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 500,
  },
  {
    name: 'ability/vehicles/barrel-roll',
    category: 'character.ability-category.vehicles',
    dependencies: [
      {
        name: 'pri-a/cr',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.primary-attribute.constitution',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'skill/vehicles/extraplanetary-flying',
        type: '',
        input: '',
        level: 5,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'skill/vehicles/intraplanetary-flying',
        type: '',
        input: '',
        level: 3,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    usesPower: true,
    powerUse: 1,
    cost: 200,
  },
  {
    name: 'ability/vehicles/broadside',
    category: 'character.ability-category.vehicles',
    dependencies: [
      {
        name: 'pri-a/in',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'skill/vehicles/extraplanetary-flying',
        type: '',
        input: '',
        level: 5,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'skill/vehicles/intraplanetary-flying',
        type: '',
        input: '',
        level: 3,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    usesPower: true,
    powerUse: 1,
    cost: 200,
  },
  {
    name: 'ability/vehicles/dive-attack',
    category: 'character.ability-category.vehicles',
    dependencies: [
      {
        name: 'pri-a/cr',
        type: '',
        input: '',
        level: 13,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'pri-a/in',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'skill/vehicles/extraplanetary-flying',
        type: '',
        input: '',
        level: 5,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'skill/vehicles/intraplanetary-flying',
        type: '',
        input: '',
        level: 3,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    usesPower: true,
    powerUse: 2,
    cost: 200,
  },
  {
    name: 'ability/vehicles/flying-ace',
    category: 'character.ability-category.vehicles',
    dependencies: [
      {
        name: 'pri-a/in',
        type: '',
        input: '',
        level: 13,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.primary-attribute.constitution',
        type: '',
        input: '',
        level: 15,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'skill/vehicles/extraplanetary-flying',
        type: '',
        input: '',
        level: 10,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'skill/vehicles/intraplanetary-flying',
        type: '',
        input: '',
        level: 5,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 500,
  },
  {
    name: 'ability/vehicles/low-level-flight',
    category: 'character.ability-category.vehicles',
    dependencies: [
      {
        name: 'pri-a/cr',
        type: '',
        input: '',
        level: 14,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/vehicles/outmaneuvering-1',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    usesPower: true,
    powerUse: 2,
    cost: 300,
  },
  {
    name: 'ability/vehicles/luring-flight',
    category: 'character.ability-category.vehicles',
    dependencies: [
      {
        name: 'pri-a/cr',
        type: '',
        input: '',
        level: 14,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/vehicles/barrel-roll',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 1,
    usesPower: true,
    powerUse: 2,
    cost: 200,
  },
  {
    name: 'ability/vehicles/onboard-marksman-1',
    category: 'character.ability-category.ranged',
    dependencies: [
      {
        name: 'skill/combat/onboard-weapons',
        type: '',
        input: '',
        level: 5,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 1,
    usesPower: true,
    powerUse: 1,
    cost: 100,
  },
  {
    name: 'ability/vehicles/onboard-marksman-2',
    category: 'character.ability-category.ranged',
    dependencies: [
      {
        name: 'skill/combat/onboard-weapons',
        type: '',
        input: '',
        level: 7,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/vehicles/onboard-marksman-1',
        type: '',
        input: '',
        level: 7,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 2,
    usesPower: true,
    powerUse: 2,
    cost: 200,
  },
  {
    name: 'ability/vehicles/onboard-marksman-3',
    category: 'character.ability-category.ranged',
    dependencies: [
      {
        name: 'skill/combat/onboard-weapons',
        type: '',
        input: '',
        level: 10,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/vehicles/onboard-marksman-2',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 3,
    usesPower: true,
    powerUse: 3,
    cost: 400,
  },
  {
    name: 'ability/vehicles/outmaneuvering-1',
    category: 'character.ability-category.vehicles',
    dependencies: [
      {
        name: 'pri-a/cr',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'pri-a/in',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'skill/vehicles/extraplanetary-flying',
        type: '',
        input: '',
        level: 7,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'skill/vehicles/intraplanetary-flying',
        type: '',
        input: '',
        level: 5,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    usesPower: true,
    powerUse: 2,
    cost: 200,
  },
  {
    name: 'ability/vehicles/outmaneuvering-2',
    category: 'character.ability-category.vehicles',
    dependencies: [
      {
        name: 'pri-a/in',
        type: '',
        input: '',
        level: 15,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'character.primary-attribute.constitution',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/vehicles/outmaneuvering-1',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    usesPower: true,
    powerUse: 3,
    cost: 200,
  },
  {
    name: 'ability/vehicles/rapid-turnaround',
    category: 'character.ability-category.vehicles',
    dependencies: [
      {
        name: 'pri-a/cr',
        type: '',
        input: '',
        level: 15,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'ability/vehicles/barrel-roll',
        type: '',
        input: '',
        level: 0,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: true,
    castTime: 2,
    usesPower: true,
    powerUse: 3,
    cost: 300,
  },
  {
    name: 'ability/vehicles/save-driving-land-vehicles',
    category: 'character.ability-category.vehicles',
    dependencies: [
      {
        name: 'pri-a/cr',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'pri-a/in',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'skill/vehicles/land-vehicles',
        type: '',
        input: '',
        level: 7,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 100,
  },
  {
    name: 'ability/vehicles/save-driving-water-vehicles',
    category: 'character.ability-category.vehicles',
    dependencies: [
      {
        name: 'pri-a/cr',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'pri-a/in',
        type: '',
        input: '',
        level: 12,
        overrideCurrent: false,
        oldLevel: 0,
      },
      {
        name: 'skill/vehicles/water-vehicles',
        type: '',
        input: '',
        level: 7,
        overrideCurrent: false,
        oldLevel: 0,
      },
    ],
    isActive: false,
    usesPower: false,
    cost: 100,
  },
];
