import type { Blueprint } from '@/base/game-object';
import type { CharacterOrigin } from '@/game-objects/character/origin/origin.go';

export const characterOrigins: Blueprint<CharacterOrigin>[] = [
  {
    name: 'character.origin.earth-urban',
    suitableTraits: [],
    primaryAttributeBonuses: { 'character.primary-attribute.charisma': 1 },
    fixedSkillBonuses: {
      'skill.combat.pistols': 1,
      'skill.crafting.computers': 3,
      'skill.crafting.cooking': 1,
      'skill.knowledge.general-knowledge': 2,
      'skill.knowledge.orientation': 1,
      'skill.social.judgement': 1,
      'skill.social.reasoning': 1,
      'skill.social.self-control': 1,
      'skill.social.soft-skills': 2,
      'skill.social.trading': 1,
    },
    selectableSkillBonuses: [
      {
        value: 1,
        skills: ['skill.combat.melee-hands', 'skill.combat.melee-weapons', 'skill.combat.throwing'],
      },
      {
        value: 1,
        skills: [
          'skill.vehicles.extraplanetary-flying',
          'skill.vehicles.intraplanetary-flying',
          'skill.vehicles.land-vehicles',
          'skill.vehicles.water-vehicles',
        ],
      },
      {
        value: 1,
        skills: [
          'skill.knowledge.astronomy',
          'skill.knowledge.biology-and-medicine',
          'skill.knowledge.chemistry',
          'skill.knowledge.electronics',
          'skill.knowledge.geology',
          'skill.knowledge.history',
          'skill.knowledge.informatics',
          'skill.knowledge.law',
          'skill.knowledge.mathematics-and-economy',
          'skill.knowledge.physics-and-mechanics',
          'skill.knowledge.spaceflight',
        ],
      },
      {
        value: 1,
        skills: ['skill.knowledge.art', 'skill.knowledge.gaming', 'skill.knowledge.music'],
      },
    ],
  },
  {
    name: 'character.origin.earth-rural',
    suitableTraits: [],
    primaryAttributeBonuses: { 'character.primary-attribute.agility': 1 },
    fixedSkillBonuses: {
      'skill.combat.pistols': 1,
      'skill.crafting.cooking': 1,
      'skill.crafting.material-processing': 2,
      'skill.knowledge.orientation': 1,
      'skill.physical.climbing': 1,
      'skill.physical.inebriating': 1,
      'skill.physical.perception': 1,
      'skill.physical.running': 1,
      'skill.physical.swimming': 1,
    },
    selectableSkillBonuses: [
      {
        value: 1,
        skills: ['skill.combat.melee-hands', 'skill.combat.throwing'],
      },
      {
        value: 1,
        skills: ['skill.combat.energy-weapons', 'skill.combat.rifles'],
      },
      {
        value: 1,
        skills: [
          'skill.vehicles.intraplanetary-flying',
          'skill.vehicles.land-vehicles',
          'skill.vehicles.water-vehicles',
        ],
      },
    ],
  },
  {
    name: 'character.origin.mars',
    suitableTraits: [],
    primaryAttributeBonuses: { 'character.primary-attribute.courage': 1 },
    fixedSkillBonuses: {
      'skill.combat.pistols': 1,
      'skill.crafting.computers': 1,
      'skill.knowledge.orientation': 3,
      'skill.physical.body-control': 2,
      'skill.physical.inebriating': 1,
      'skill.physical.perception': 1,
      'skill.physical.running': 1,
    },
    selectableSkillBonuses: [
      {
        value: 2,
        skills: ['skill.combat.melee-hands', 'skill.combat.melee-weapons', 'skill.combat.throwing'],
      },
      {
        value: 1,
        skills: ['skill.combat.energy-weapons', 'skill.combat.onboard-weapons', 'skill.combat.rifles'],
      },
      {
        value: 1,
        skills: [
          'skill.knowledge.electronics',
          'skill.knowledge.gaming',
          'skill.knowledge.geology',
          'skill.knowledge.informatics',
          'skill.knowledge.law',
          'skill.knowledge.mathematics-and-economy',
          'skill.knowledge.physics-and-mechanics',
          'skill.knowledge.spaceflight',
          'skill.knowledge.survival',
        ],
      },
    ],
  },
  {
    name: 'character.origin.venus',
    suitableTraits: [],
    primaryAttributeBonuses: { 'character.primary-attribute.dexterity': 1 },
    fixedSkillBonuses: {
      'skill.combat.melee-hands': 1,
      'skill.combat.pistols': 2,
      'skill.crafting.computers': 1,
      'skill.crafting.cooking': 1,
      'skill.crafting.disguising': 1,
      Skill_Crafting_Writing: 1,
      'skill.knowledge.general-knowledge': 2,
      'skill.physical.inebriating': 1,
      'skill.physical.perception': 2,
      'skill.social.judgement': 1,
      'skill.social.reasoning': 1,
      'skill.social.self-control': 1,
      'skill.social.soft-skills': 3,
    },
    selectableSkillBonuses: [
      {
        value: 1,
        skills: ['skill.physical.acting', 'skill.social.flirting', 'skill.social.inspiring'],
      },
      {
        value: 1,
        skills: ['skill.knowledge.art', 'skill.knowledge.gaming', 'skill.knowledge.music'],
      },
    ],
  },
  {
    name: 'character.origin.ceres',
    suitableTraits: [],
    primaryAttributeBonuses: { 'character.primary-attribute.intuition': 1 },
    fixedSkillBonuses: {
      'skill.combat.melee-hands': 1,
      'skill.combat.pistols': 1,
      'skill.crafting.computers': 2,
      'skill.crafting.cooking': 1,
      'skill.crafting.material-processing': 2,
      'skill.knowledge.general-knowledge': 1,
      'skill.physical.inebriating': 2,
      'skill.physical.perception': 1,
      'skill.social.judgement': 1,
      'skill.social.reasoning': 1,
      'skill.social.trading': 3,
      'skill.vehicles.extraplanetary-flying': 3,
    },
    selectableSkillBonuses: [
      {
        value: 1,
        skills: [
          'skill.knowledge.astronomy',
          'skill.knowledge.electronics',
          'skill.knowledge.geology',
          'skill.knowledge.informatics',
          'skill.knowledge.law',
          'skill.knowledge.mathematics-and-economy',
          'skill.knowledge.physics-and-mechanics',
          'skill.knowledge.spaceflight',
        ],
      },
    ],
  },
  {
    name: 'character.origin.europa',
    suitableTraits: [],
    primaryAttributeBonuses: { 'character.primary-attribute.cleverness': 1 },
    fixedSkillBonuses: {
      'skill.crafting.computers': 3,
      'skill.crafting.cooking': 1,
      Skill_Crafting_Writing: 1,
      'skill.knowledge.general-knowledge': 3,
      'skill.physical.swimming': 2,
      'skill.social.judgement': 1,
      'skill.social.reasoning': 3,
      'skill.social.self-control': 1,
      'skill.social.soft-skills': 2,
    },
    selectableSkillBonuses: [
      {
        value: 1,
        skills: [
          'skill.knowledge.astronomy',
          'skill.knowledge.biology-and-medicine',
          'skill.knowledge.chemistry',
          'skill.knowledge.geology',
          'skill.knowledge.informatics',
          'skill.knowledge.mathematics-and-economy',
          'skill.knowledge.physics-and-mechanics',
          'skill.knowledge.spaceflight',
        ],
      },
      {
        value: 1,
        skills: [
          'skill.knowledge.art',
          'skill.knowledge.gaming',
          'skill.knowledge.history',
          'skill.knowledge.law',
          'skill.knowledge.music',
          'skill.knowledge.tactics-and-strategy',
        ],
      },
    ],
  },
  {
    name: 'character.origin.ganymede',
    suitableTraits: [],
    primaryAttributeBonuses: { 'character.primary-attribute.constitution': 1 },
    fixedSkillBonuses: {
      'skill.combat.pistols': 1,
      'skill.crafting.cooking': 2,
      'skill.crafting.material-processing': 3,
      'skill.knowledge.survival': 1,
      'skill.physical.body-control': 1,
      'skill.physical.climbing': 2,
      'skill.physical.inebriating': 1,
      'skill.physical.running': 1,
      'skill.social.judgement': 2,
      'skill.social.self-control': 1,
      'skill.social.trading': 2,
      'skill.vehicles.land-vehicles': 1,
    },
    selectableSkillBonuses: [
      {
        value: 2,
        skills: ['skill.combat.melee-hands', 'skill.combat.melee-weapons', 'skill.combat.throwing'],
      },
    ],
  },
  {
    name: 'character.origin.titan',
    suitableTraits: [],
    primaryAttributeBonuses: { 'character.primary-attribute.strength': 1 },
    fixedSkillBonuses: {
      'skill.combat.melee-hands': 3,
      'skill.crafting.computers': 1,
      'skill.crafting.material-processing': 3,
      'skill.knowledge.orientation': 1,
      'skill.physical.body-control': 1,
      'skill.physical.inebriating': 3,
      'skill.physical.running': 1,
      'skill.social.judgement': 1,
      'skill.social.trading': 1,
    },
    selectableSkillBonuses: [
      {
        value: 1,
        skills: ['skill.combat.energy-weapons', 'skill.combat.onboard-weapons', 'skill.combat.rifles'],
      },
      {
        value: 1,
        skills: ['skill.vehicles.intraplanetary-flying', 'skill.vehicles.land-vehicles'],
      },
      {
        value: 1,
        skills: [
          'skill.knowledge.chemistry',
          'skill.knowledge.electronics',
          'skill.knowledge.geology',
          'skill.knowledge.informatics',
          'skill.knowledge.physics-and-mechanics',
          'skill.knowledge.spaceflight',
        ],
      },
    ],
  },
  {
    name: 'character.origin.miranda',
    suitableTraits: [],
    primaryAttributeBonuses: { 'character.primary-attribute.courage': 1 },
    fixedSkillBonuses: {
      'skill.combat.pistols': 1,
      'skill.crafting.computers': 2,
      'skill.knowledge.general-knowledge': 1,
      'skill.knowledge.history': 1,
      'skill.social.inspiring': 1,
      'skill.social.judgement': 1,
      'skill.social.reasoning': 2,
      'skill.social.soft-skills': 1,
      'skill.social.trading': 3,
      'skill.vehicles.extraplanetary-flying': 1,
    },
    selectableSkillBonuses: [
      {
        value: 1,
        skills: [
          'skill.knowledge.art',
          'skill.knowledge.biology-and-medicine',
          'skill.knowledge.chemistry',
          'skill.knowledge.electronics',
          'skill.knowledge.gaming',
          'skill.knowledge.geology',
          'skill.knowledge.informatics',
          'skill.knowledge.mathematics-and-economy',
          'skill.knowledge.music',
          'skill.knowledge.spaceflight',
        ],
      },
    ],
  },
  {
    name: 'character.origin.codex-triton',
    suitableTraits: [],
    primaryAttributeBonuses: { 'character.primary-attribute.intuition': 1 },
    fixedSkillBonuses: {
      'skill.combat.pistols': 1,
      'skill.crafting.computers': 1,
      'skill.knowledge.general-knowledge': 3,
      'skill.physical.body-control': 1,
      'skill.social.judgement': 1,
      'skill.social.reasoning': 2,
      'skill.social.soft-skills': 1,
    },
    selectableSkillBonuses: [
      {
        value: 2,
        skills: ['skill.combat.melee-weapons', 'skill.combat.throwing'],
      },
      {
        value: 1,
        skills: ['skill.combat.energy-weapons', 'skill.combat.onboard-weapons', 'skill.combat.rifles'],
      },
      {
        value: 1,
        skills: [
          'skill.vehicles.extraplanetary-flying',
          'skill.vehicles.intraplanetary-flying',
          'skill.vehicles.land-vehicles',
        ],
      },
      {
        value: 1,
        skills: [
          'skill.knowledge.art',
          'skill.knowledge.astronomy',
          'skill.knowledge.biology-and-medicine',
          'skill.knowledge.chemistry',
          'skill.knowledge.electronics',
          'skill.knowledge.history',
          'skill.knowledge.informatics',
          'skill.knowledge.mathematics-and-economy',
          'skill.knowledge.music',
          'skill.knowledge.physics-and-mechanics',
          'skill.knowledge.spaceflight',
          'skill.knowledge.tactics-and-strategy',
        ],
      },
    ],
  },
  {
    name: 'character.origin.codex-moons',
    suitableTraits: [],
    primaryAttributeBonuses: { 'character.primary-attribute.strength': 1 },
    fixedSkillBonuses: {
      'skill.combat.melee-hands': 2,
      'skill.crafting.cooking': 1,
      'skill.crafting.material-processing': 3,
      'skill.physical.body-control': 3,
      'skill.physical.climbing': 2,
      'skill.physical.inebriating': 2,
      'skill.physical.perception': 1,
      'skill.physical.running': 1,
      'skill.social.judgement': 1,
      'skill.social.self-control': 1,
      'skill.social.trading': 1,
      'skill.vehicles.land-vehicles': 1,
    },
    selectableSkillBonuses: [
      {
        value: 2,
        skills: ['skill.combat.melee-weapons', 'skill.combat.throwing'],
      },
      {
        value: 1,
        skills: [
          'skill.knowledge.chemistry',
          'skill.knowledge.electronics',
          'skill.knowledge.gaming',
          'skill.knowledge.geology',
          'skill.knowledge.informatics',
          'skill.knowledge.physics-and-mechanics',
          'skill.knowledge.spaceflight',
          'skill.knowledge.survival',
        ],
      },
    ],
  },
];
